<?php

namespace App\Http\Controllers;

use App\Models\Report;
use App\Models\ReportImage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

/**
 * ReportImageController
 *
 * Serves report images securely from the private 'local' disk.
 * Access control is enforced via Laravel Signed URLs generated by the API resource,
 * meaning no session cookies or tokens are required by the frontend <img> tag.
 */
class ReportImageController extends Controller
{
    public function show(Request $request, Report $report, ReportImage $image): mixed
    {
        // Ensure the image actually belongs to the requested report
        if ($image->report_id !== $report->id) {
            return response()->json(['message' => 'Image not found.'], 404);
        }

        if (!Storage::disk('local')->exists($image->image_path)) {
            return response()->json(['message' => 'Image file not found.'], 404);
        }

        // Stream the file directly from the private disk
        return Storage::disk('local')->response($image->image_path);
    }
}
